# Dockerfile.zeppelin

# Usa la imagen base de Zeppelin
FROM apache/zeppelin:0.10.0

# Copia el notebook y el archivo CSV al directorio de trabajo del contenedor
COPY //c/Users/josan/Documents/GitHub/EDEM_MDA2324/Alumnos/ES/Josan_Rodrigo_Cortes/Spark/e2e_spark/RealEstateDataset.csv /mynotebook/
COPY //c/Users/josan/Documents/GitHub/EDEM_MDA2324/Alumnos/ES/Josan_Rodrigo_Cortes/Spark/e2e_spark/PostWork/TrabajoSpark.ipynb /mynotebook/
