# coding: utf-8

# flake8: noqa
"""
    Api información del sensor de los robots

    Esta API nos proporciona la información almacenada en la base de datos de la empresa Ejemplo de cada uno de sus sensores  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.inline_response200 import InlineResponse200
