FROM apache/apache/spark:3.5.0

COPY /C/Users/josan/Documents/GitHub/EDEM_MDA2324/Alumnos/ES/Josan_Rodrigo_Cortes/Spark/e2e_spark/PostWork/nuevodocker/trabajospark.py /codigo/trabajospark.py

EXPOSE 4040