alumnos=[
    {
        "Nombre":"Josan",
     "Apellido1":"Rodrigo",
     "Apellido2":"Cortes",
     "NIF":"1",
     "Email":"josan@email.com",
     "Calificacion":False
    },
    {
        "Nombre":"Laura",
     "Apellido1":"Jimenez",
     "Apellido2":"Ruiz",
     "NIF":"2",
     "Email":"laura@email.com",
     "Calificacion":False
    },
    {
        "Nombre":"Josan",
     "Apellido1":"Rodrigo",
     "Apellido2":"Jimenez",
     "NIF":"3",
     "Email":"josan2@email.com",
     "Calificacion":True
    },
    {
        "Nombre":"Claudio",
     "Apellido1":"Rodrigo",
     "Apellido2":"Jimenez",
     "NIF":"4",
     "Email":"claudio@email.com",
     "Calificacion":True
    }
    ]