FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

#no sé aquí qué está fallando

ENTRYPOINT [ python , /Users/jesus/Documents/GitHub/EDEM_MDA2324/Alumnos/FS/Jesus Jornet Orti/Ahorcado/Ahorcado.py ]