FROM python:3
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY main.py .
COPY Clase_venta.py .
COPY Creacion_streams_KSQL.py .
COPY Creacion_topics.py .
COPY Productor_inicial.py .
ENTRYPOINT ["python", "./main.py" ]