openapi: 3.0.0
info:
  title: Robot Temperature Sensor API
  description: API to retrieve temperature measurements from a robot sensor
  version: 1.0.0
servers:
- url: /
paths:
  /getLastMeassureBySensor/{sensor}:
    get:
      summary: Get last temperature measurement by sensor ID
      operationId: get_last_meassure_by_sensor_sensor_get
      parameters:
      - name: sensor
        in: path
        description: ID of the sensor
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measure'
        "400":
          description: Sensor not found
        "404":
          description: Invalid ID supplied
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Measure:
      type: object
      properties:
        code:
          type: string
          description: ID of the sensor
        fechamuestreo:
          type: string
          description: Date and time of the measurement
        unidad:
          type: string
          description: Unit of measurement
        medicion:
          type: number
          description: Temperature measurement
      example:
        unidad: unidad
        medicion: 0.80082819046101150206595775671303272247314453125
        code: code
        fechamuestreo: fechamuestreo

