# -*- coding: utf-8 -*-
"""Spotifydaset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qb4wHZULF5Toic3HcYLyp6SiHm-DFSH9

# Spotify Dataset

## En este dataset vamos a analizar los datos obtenidos de kaggle sobre Spotify

Importamos las librerías necesarias
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Definimos el dataframe"""

spotifyDf=pd.read_csv("/content/train.csv",delimiter=",")
print(spotifyDf.head(50).to_markdown())

"""## Vamos a ver que tenemos:

"""

spotifyDf.describe()

"""Según los parámetro que nos devuelve la función describe() nuestro dataset nos define diferentes aspectos como la energía, la acústica, la bailabilidad, etc, de casi 42.000 canciones.

A partir de este punto nos centraremos en analizar la popularidad tanto de canciones como de generos, entendiendo que carece de valor para el caso, el analisis del resto de variables de cada canción, puesto que no somos expertos...

## Canciones mas populares
"""

dfMasPopulares = spotifyDf.sort_values(by='popularity', ascending=False)
print(dfMasPopulares.head(30).to_markdown())

"""## Vamos a ver la popularidad de cada genero

"""

df_valoraciones = spotifyDf.groupby('track_genre')['popularity'].mean().reset_index()

df_valoraciones = df_valoraciones.sort_values(by='popularity', ascending=False)

print(df_valoraciones)

"""# Los generos mejor valorados"""

df_valoraciones_top10 = df_valoraciones.head(20)
plt.figure(figsize=(12, 8))
plt.bar(df_valoraciones_top10['track_genre'], df_valoraciones_top10['popularity'],width=0.6)
plt.xlabel('Género')
plt.ylabel('Media de Valoraciones')
plt.title('Generos mejor valorados')
plt.xticks(rotation=90)
plt.show()

"""## Los generos peor valorados

"""

df_valoraciones_top10 = df_valoraciones.tail(20)

plt.bar(df_valoraciones_top10['track_genre'], df_valoraciones_top10['popularity'])
plt.xlabel('Género')
plt.ylabel('Media de Valoraciones')
plt.title('Los generos peor valorados')
plt.xticks(rotation=90)
plt.show()

"""## Las canciones mejor valoradas"""

df_top20 = spotifyDf.sort_values(by='popularity', ascending=False).head(20)
print(df_top20.to_markdown())

plt.scatter(df_top20['track_name'], df_top20['popularity'])
plt.xlabel('Nombre de la Canción')
plt.ylabel('Valoración')
plt.title('Valoración de las mejores canciones ')
plt.xticks(rotation=45, ha="right")  # Ajusta el ángulo de rotación según tus preferencias
plt.show()

"""## Las canciones peor valoradas"""

df_lesstop20 = spotifyDf.sort_values(by='popularity', ascending=False).tail(20)
print(df_lesstop20.to_markdown())
df_lesstop20 = df_lesstop20.dropna()

plt.scatter(df_lesstop20['track_name'], df_lesstop20['popularity'])
plt.xlabel('Nombre de la Canción')
plt.ylabel('Valoración')
plt.title('Valoración de las peores 20 Canciones ')
plt.xticks(rotation=45, ha="right")  # Ajusta el ángulo de rotación según tus preferencias
plt.show()

"""## Los mejores albumes"""

df_top20Albumes = spotifyDf.sort_values(by='popularity', ascending=False).head(20)

plt.scatter(df_top20Albumes['album_name'], df_top20Albumes['popularity'])
plt.xlabel('Nombre de la Canción')
plt.ylabel('Valoración')
plt.title('Los mejores albumes ')
plt.xticks(rotation=45, ha="right")
plt.subplots_adjust(bottom=0.2)
plt.show()

"""## Los peores albumes"""

df_lesstop20Albumes = spotifyDf.sort_values(by='popularity', ascending=False).tail(20)

plt.scatter(df_lesstop20Albumes['album_name'], df_lesstop20Albumes['popularity'])
plt.xlabel('Nombre de la Canción')
plt.ylabel('Valoración')
plt.title('Los mejores albumes ')
plt.xticks(rotation=45, ha="right")
plt.subplots_adjust(bottom=0.2)
plt.show()

"""## Según los datos obtenidos de kaggle y el analisis realizado, hemos visto cuales son las canciones, albumes y generos mejor y peor valorados.
## Podríamos haber analizado tambien el resto de variables, e intentar buscar correlaciones entre estilos de musica y las diferentes características mostradas de cada canción en los datos. Pero sintiendolo mucho, es algo que en este momento del master, se me escapa.
## Josan Rodrigo Cortés

"""