FROM alpine:latest

#RUN pip install --upgrade pip
#RUN apt-get update
#RUN apt-get upgrade -y
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
COPY requirements.txt /
COPY entrypoint.sh /
COPY pysum.py /
RUN chmod +rwx /pysum.py
RUN chmod +rwx /entrypoint.sh
ENTRYPOINT ["python3", "/pysum.py"]