# coding: utf-8

"""
    Api información del sensor de los robots

    Esta API nos proporciona la información almacenada en la base de datos de la empresa Ejemplo de cada uno de sus sensores  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sensor_api import SensorApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSensorApi(unittest.TestCase):
    """SensorApi unit test stubs"""

    def setUp(self):
        self.api = SensorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sensor_get(self):
        """Test case for sensor_get

        Obtiene la información almacenada de los datos de un sensor  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
