openapi: 3.0.0
info:
  title: API de Monitorizacion Temperaturas del Rbot
  description: API para acceder a las mediciones de temepratura
  version: 1.0.0
paths:
  /getLastMeassureBySensor/{sensor}:
    parameters:
      - in: path
        name: sensor
        required: true
        schema:
          type: string
        description: id sensor
    get:
      summary: obtener medicion sensor de temperatura
      responses:
        '200':
          description: medicion bien obtenida
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: id sensor
                  fechamuestreo:
                    type: string
                    description: fecha hora medicion
                  unidad:
                    type: string
                    description: unidad medicion
                  medicion:
                    type: number
                    description: valor medicion
        '400':
          description: Sensor not found
        '404':
          description: Invalid ID supplied