utmb_18DF = spark.read.option("header", "true").option("delimiter", ";").csv("utmb_18.csv")
utmb_19DF = spark.read.option("header", "true").option("delimiter", ";").csv("utmb_19.csv")
utmb_21DF = spark.read.option("header", "true").option("delimiter", ";").csv("utmb_21.csv")
utmb_22DF = spark.read.option("header", "true").option("delimiter", ";").csv("utmb_22.csv")
utmb_23DF = spark.read.option("header", "true").option("delimiter", ";").csv("utmb_23.csv")
utmb_18DF.show()
utmb_19DF.show()
utmb_21DF.show()
utmb_22DF.show()
utmb_23DF.show()