version: '3'
services:
  srv-nginx:
    image: nginx
    ports:
      - "80:80"

  srv-python:
    image: python:3.8
    command: python -m http.server 8000
    ports:
      - "8000:8000"
    volumes:
      - ./tu_codigo_python:/app  # Ajusta la ruta a tu código Python
    working_dir: /app
