# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Medicion(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, fechamuestreo: str=None, unidad: str=None, medicion: float=None):  # noqa: E501
        """Medicion - a model defined in Swagger

        :param code: The code of this Medicion.  # noqa: E501
        :type code: str
        :param fechamuestreo: The fechamuestreo of this Medicion.  # noqa: E501
        :type fechamuestreo: str
        :param unidad: The unidad of this Medicion.  # noqa: E501
        :type unidad: str
        :param medicion: The medicion of this Medicion.  # noqa: E501
        :type medicion: float
        """
        self.swagger_types = {
            'code': str,
            'fechamuestreo': str,
            'unidad': str,
            'medicion': float
        }

        self.attribute_map = {
            'code': 'code',
            'fechamuestreo': 'fechamuestreo',
            'unidad': 'unidad',
            'medicion': 'medicion'
        }

        self._code = code
        self._fechamuestreo = fechamuestreo
        self._unidad = unidad
        self._medicion = medicion

    @classmethod
    def from_dict(cls, dikt) -> 'Medicion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Medicion of this Medicion.  # noqa: E501
        :rtype: Medicion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this Medicion.

        El identificador único del sensor.  # noqa: E501

        :return: The code of this Medicion.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Medicion.

        El identificador único del sensor.  # noqa: E501

        :param code: The code of this Medicion.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def fechamuestreo(self) -> str:
        """Gets the fechamuestreo of this Medicion.

        La fecha y hora en la que se realizó la medición.  # noqa: E501

        :return: The fechamuestreo of this Medicion.
        :rtype: str
        """
        return self._fechamuestreo

    @fechamuestreo.setter
    def fechamuestreo(self, fechamuestreo: str):
        """Sets the fechamuestreo of this Medicion.

        La fecha y hora en la que se realizó la medición.  # noqa: E501

        :param fechamuestreo: The fechamuestreo of this Medicion.
        :type fechamuestreo: str
        """
        if fechamuestreo is None:
            raise ValueError("Invalid value for `fechamuestreo`, must not be `None`")  # noqa: E501

        self._fechamuestreo = fechamuestreo

    @property
    def unidad(self) -> str:
        """Gets the unidad of this Medicion.

        La unidad de medida de la temperatura (por ejemplo, Celsius, Fahrenheit).  # noqa: E501

        :return: The unidad of this Medicion.
        :rtype: str
        """
        return self._unidad

    @unidad.setter
    def unidad(self, unidad: str):
        """Sets the unidad of this Medicion.

        La unidad de medida de la temperatura (por ejemplo, Celsius, Fahrenheit).  # noqa: E501

        :param unidad: The unidad of this Medicion.
        :type unidad: str
        """
        if unidad is None:
            raise ValueError("Invalid value for `unidad`, must not be `None`")  # noqa: E501

        self._unidad = unidad

    @property
    def medicion(self) -> float:
        """Gets the medicion of this Medicion.

        El valor de la medición de temperatura.  # noqa: E501

        :return: The medicion of this Medicion.
        :rtype: float
        """
        return self._medicion

    @medicion.setter
    def medicion(self, medicion: float):
        """Sets the medicion of this Medicion.

        El valor de la medición de temperatura.  # noqa: E501

        :param medicion: The medicion of this Medicion.
        :type medicion: float
        """
        if medicion is None:
            raise ValueError("Invalid value for `medicion`, must not be `None`")  # noqa: E501

        self._medicion = medicion
