# Usa una imagen de Python como base
FROM python:3.8-slim

# Copia el script Python al directorio de trabajo en la imagen
COPY suma.py /suma.py

# Ejecuta el script cuando se inicie el contenedor
ENTRYPOINT ["python", "/suma.py"]







