# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: str=None, fechamuestreo: str=None, unidad: str=None, medicion: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param code: The code of this InlineResponse200.  # noqa: E501
        :type code: str
        :param fechamuestreo: The fechamuestreo of this InlineResponse200.  # noqa: E501
        :type fechamuestreo: str
        :param unidad: The unidad of this InlineResponse200.  # noqa: E501
        :type unidad: str
        :param medicion: The medicion of this InlineResponse200.  # noqa: E501
        :type medicion: str
        """
        self.swagger_types = {
            'code': str,
            'fechamuestreo': str,
            'unidad': str,
            'medicion': str
        }

        self.attribute_map = {
            'code': 'code',
            'fechamuestreo': 'fechamuestreo',
            'unidad': 'unidad',
            'medicion': 'medicion'
        }
        self._code = code
        self._fechamuestreo = fechamuestreo
        self._unidad = unidad
        self._medicion = medicion

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this InlineResponse200.

        ID del sensor  # noqa: E501

        :return: The code of this InlineResponse200.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this InlineResponse200.

        ID del sensor  # noqa: E501

        :param code: The code of this InlineResponse200.
        :type code: str
        """

        self._code = code

    @property
    def fechamuestreo(self) -> str:
        """Gets the fechamuestreo of this InlineResponse200.

        Fecha de muestreo  # noqa: E501

        :return: The fechamuestreo of this InlineResponse200.
        :rtype: str
        """
        return self._fechamuestreo

    @fechamuestreo.setter
    def fechamuestreo(self, fechamuestreo: str):
        """Sets the fechamuestreo of this InlineResponse200.

        Fecha de muestreo  # noqa: E501

        :param fechamuestreo: The fechamuestreo of this InlineResponse200.
        :type fechamuestreo: str
        """

        self._fechamuestreo = fechamuestreo

    @property
    def unidad(self) -> str:
        """Gets the unidad of this InlineResponse200.

        Unidad de medida  # noqa: E501

        :return: The unidad of this InlineResponse200.
        :rtype: str
        """
        return self._unidad

    @unidad.setter
    def unidad(self, unidad: str):
        """Sets the unidad of this InlineResponse200.

        Unidad de medida  # noqa: E501

        :param unidad: The unidad of this InlineResponse200.
        :type unidad: str
        """

        self._unidad = unidad

    @property
    def medicion(self) -> str:
        """Gets the medicion of this InlineResponse200.

        Valor de la medición  # noqa: E501

        :return: The medicion of this InlineResponse200.
        :rtype: str
        """
        return self._medicion

    @medicion.setter
    def medicion(self, medicion: str):
        """Sets the medicion of this InlineResponse200.

        Valor de la medición  # noqa: E501

        :param medicion: The medicion of this InlineResponse200.
        :type medicion: str
        """

        self._medicion = medicion
