# Rafael Pérez Morales
# Dockerfile que ejecuta con python el archivo python_contenedores, dándole dos argumentos

FROM python:3.8-slim-buster

COPY python_contenedores.py .

CMD ["python", "python_contenedores.py", "arg1", "arg2"]