openapi: 3.0.3
info:
  title: The Ultimate Robot Temperature Listener for EDEM - TURTLE 1.0
  description: |2-

    My very unique robot temperature sensor reader server for EDEM. This work is a deliverable by Julián Merino for the Master in Big Data & Cloud. Documentation done with Swagger, based on the PetStore:

    [EDEM](https://edem.eu/master-big-data-analytics/)
  version: 1.0.0
servers:
- url: https
tags:
- name: getLastMeasureBySensor
  description: All about the temperature sensor data.
paths:
  /getLastMeasureBySensor/{sensor}:
    get:
      tags:
      - getLastMeasureBySensor
      summary: "Obtains ID, date, unit, and temperature measurement, and returns Measure\
        \ (200) or errors (400, 404)"
      operationId: get_temp
      parameters:
      - name: sensor
        in: path
        description: Finds the sensor by ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measure'
                x-content-type: application/json
        "400":
          description: Sensor not found
        "404":
          description: Invalid ID supplied
      x-openapi-router-controller: swagger_server.controllers.get_last_measure_by_sensor_controller
components:
  schemas:
    Measure:
      type: object
      properties:
        code:
          type: string
        fechamuestreo:
          type: string
        unidad:
          type: string
        medicion:
          type: number
      example:
        unidad: unidad
        medicion: 0.80082819046101150206595775671303272247314453125
        code: code
        fechamuestreo: fechamuestreo

