name: "Entregables"

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
jobs:
  entregables:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run Deliverables
        run: |
          ls -la .github
          python3 .github/code/check.py
          # git config --global user.name 'Pedro Nieto'
          # git config --global user.email 'a10pepo@github.com'
          # git commit -am "Automated report"
          # git push          
